DROP TYPE etudiant FORCE;
DROP TYPE etudiants FORCE;
DROP TYPE unites FORCE;
DROP TYPE unite FORCE;
DROP TYPE seance FORCE;
DROP TYPE seances FORCE;
DROP TYPE c2 FORCE;
DROP TYPE ensc2 FORCE;
DROP TYPE c1 FORCE;
DROP TYPE ensc1 FORCE;

DROP TABLE lesue;
DROP TABLE lesetudiants;
